---
title: "Rota_CEA_Case_1"
author: "Catherine Wenger"
date: "2024-03-09"
output: html_document
---

# Case 1 Description 
No vaccine / 6-10 (BL) / 6-10-14 / 6-10-40 / 1-6-10

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(insight)
library(openxlsx)
library(geomtextpath)
library(gghighlight)
library(gt)
library(ggplot2)
library(scales)
```

## Simulation

```{r}
# Run model 1000 times with different parameter estimates 
nsim <- 1000 

# set array 
column.names <- c("NumCases_NoVac","NumCases_Rotarix6_10","NumCases_Rotarix6_10_14",
                  "NumCases_Rotarix6_10_40","NumCases_Neonatal1_6_10",
                  "NoVacHosp", "Rotarix6_10Hosp","Rotarix6_10_14Hosp",
                  "Rotarix6_10_40Hosp","Neonatal1_6_10Hosp",
                  "NoVacDeaths", "Rotarix6_10Deaths","Rotarix6_10_14Deaths",
                  "Rotarix6_10_40Deaths","Neonatal1_6_10Deaths",
                  "NoVacCost", "Rotarix6_10Cost","Rotarix6_10_14Cost",
                  "Rotarix6_10_40Cost","Neonatal1_6_10Cost",
                  "NoVacCostInt","Rotarix6_10CostInt","Rotarix6_10_14CostInt",
                  "Rotarix6_10_40CostInt","Neonatal1_6_10CostInt",
                  "NoVacCostTrt","Rotarix6_10CostTrt","Rotarix6_10_14CostTrt",
                  "Rotarix6_10_40CostTrt","Neonatal1_6_10CostTrt",
                  "NoVacDALYs","Rotarix6_10DALYs","Rotarix6_10_14DALYs",
                  "Rotarix6_10_40DALYs","Neonatal1_6_10DALYs") 

matrix.names <- c(1:10)
row.names <- c(1:nsim)
yearData <-array(0,dim=c(nsim,35,10),
                dimnames = list(row.names,column.names,matrix.names))
YLL <- array(0, dim = c(1000, 10))
YLD <- array(0, dim = c(1000, 10))
YLLtot <- numeric(1000)
YLDtot <- numeric(1000)

params <-array(rep(1, nsim*20),dim=c(nsim,20))

colnames(params)<- c("pr_seek","pr_no_treat","pr_inpat","pr_outpat_MS","pr_outpat_NS",
                    "pr_no_treat_NS","pr_death_inpat","pr_death_outpat","pr_death_notreat",
                    "cost_vacc_Rotarix6_10","cost_vacc_Rotarix6_10_14",
                    "cost_vacc_Rotarix6_10_40","cost_vacc_Neonatal1_6_10",
                    "delRotarix","cost_in_trt","cost_out_trt_NS","cost_out_trt_MS",
                    "daly_wt_NS","daly_wt_MS","dur_inf") 

params <- as.data.frame(params)

outputArray <-array(rep(1, nsim*69),dim=c(nsim,69))

colnames(outputArray)<- c("NumCases_NoVac","NumCases_Rotarix6_10","NumCases_Rotarix6_10_14",
                          "NumCases_Rotarix6_10_40","NumCases_Neonatal1_6_10",
                          "MSCases_NoVac","MSCases_Rotarix6_10","MSCases_Rotarix6_10_14",
                          "MSCases_Rotarix6_10_40","MSCases_Neonatal1_6_10",
                          "NSCases_NoVac","NSCases_Rotarix6_10","NSCases_Rotarix6_10_14",
                          "NSCases_Rotarix6_10_40","NSCases_Neonatal1_6_10",
                          "NoVacHosp", "Rotarix6_10Hosp","Rotarix6_10_14Hosp",
                          "Rotarix6_10_40Hosp","Neonatal1_6_10Hosp",
                          "NoVacDeaths", "Rotarix6_10Deaths","Rotarix6_10_14Deaths",
                          "Rotarix6_10_40Deaths","Neonatal1_6_10Deaths",
                          "CasesAverted_Rotarix6_10","HospAverted_Rotarix6_10",
                          "DeathsAverted_Rotarix6_10",
                          "CasesAverted_Rotarix6_10_14","HospAverted_Rotarix6_10_14",
                          "DeathsAverted_Rotarix6_10_14",
                          "CasesAverted_Rotarix6_10_40","HospAverted_Rotarix6_10_40",
                          "DeathsAverted_Rotarix6_10_40",
                          "CasesAverted_Neonatal1_6_10","HospAverted_Neonatal1_6_10",
                          "DeathsAverted_Neonatal1_6_10",
                          "NoVacCost", "Rotarix6_10Cost","Rotarix6_10_14Cost",
                          "Rotarix6_10_40Cost","Neonatal1_6_10Cost",
                          "NoVacCostInt","Rotarix6_10CostInt","Rotarix6_10_14CostInt",
                          "Rotarix6_10_40CostInt","Neonatal1_6_10CostInt",
                          "NoVacCostTrt","Rotarix6_10CostTrt","Rotarix6_10_14CostTrt",
                          "Rotarix6_10_40CostTrt","Neonatal1_6_10CostTrt",
                          "NoVacDALYs","Rotarix6_10DALYs","Rotarix6_10_14DALYs",
                          "Rotarix6_10_40DALYs","Neonatal1_6_10DALYs",
                          "CERatioY_NoVac","CERatioY_Rotarix6_10_14",
                          "CERatioY_Rotarix6_10_40","CERatioY_Neonatal1_6_10",
                          "CERatioX_NoVac","CERatioX_Rotarix6_10_14",
                          "CERatioX_Rotarix6_10_40","CERatioX_Neonatal1_6_10",
                          "ICERatio_Neonatal1_6_10","ICERatio_Rotarix6_10",
                          "ICERatio_Rotarix6_10_14","ICERatio_Rotarix6_10_40") 

outputArray <- as.data.frame(outputArray)
```

#Import TDM simulation data
```{r, warning=FALSE}
load("TDMdata.Rdata")
    Yr0MSNoVac <- TDMdata[["Yr0MSNoVac"]]
    Yr0NSNoVac <- TDMdata[["Yr0NSNoVac"]]
    Yr1MSNoVac <- TDMdata[["Yr1MSNoVac"]]
    Yr1NSNoVac <- TDMdata[["Yr1NSNoVac"]]
    Yr2MSNoVac <- TDMdata[["Yr2MSNoVac"]]
    Yr2NSNoVac <- TDMdata[["Yr2NSNoVac"]]
    Yr3MSNoVac <- TDMdata[["Yr3MSNoVac"]]
    Yr3NSNoVac <- TDMdata[["Yr3NSNoVac"]]
    Yr4MSNoVac <- TDMdata[["Yr4MSNoVac"]]
    Yr4NSNoVac <- TDMdata[["Yr4NSNoVac"]]
    
    Yr0MS6_10 <- TDMdata[["Yr0MS6_10"]]
    Yr0NS6_10 <- TDMdata[["Yr0NS6_10"]]
    Yr1MS6_10 <- TDMdata[["Yr1MS6_10"]]
    Yr1NS6_10 <- TDMdata[["Yr1NS6_10"]]
    Yr2MS6_10 <- TDMdata[["Yr2MS6_10"]]
    Yr2NS6_10 <- TDMdata[["Yr2NS6_10"]]
    Yr3MS6_10 <- TDMdata[["Yr3MS6_10"]]
    Yr3NS6_10 <- TDMdata[["Yr3NS6_10"]]
    Yr4MS6_10 <- TDMdata[["Yr4MS6_10"]]
    Yr4NS6_10 <- TDMdata[["Yr4NS6_10"]]
    NumDoses6_10 <- TDMdata[["NumDoses6_10"]]
    
    Yr0MS6_10_14 <- TDMdata[["Yr0MS6_10_14"]]
    Yr0NS6_10_14 <- TDMdata[["Yr0NS6_10_14"]]
    Yr1MS6_10_14 <- TDMdata[["Yr1MS6_10_14"]]
    Yr1NS6_10_14 <- TDMdata[["Yr1NS6_10_14"]]
    Yr2MS6_10_14 <- TDMdata[["Yr2MS6_10_14"]]
    Yr2NS6_10_14 <- TDMdata[["Yr2NS6_10_14"]]
    Yr3MS6_10_14 <- TDMdata[["Yr3MS6_10_14"]]
    Yr3NS6_10_14 <- TDMdata[["Yr3NS6_10_14"]]
    Yr4MS6_10_14 <- TDMdata[["Yr4MS6_10_14"]]
    Yr4NS6_10_14 <- TDMdata[["Yr4NS6_10_14"]]
    NumDoses6_10_14 <- TDMdata[["NumDoses6_10_14"]]
    
    Yr0MS6_10_40 <- TDMdata[["Yr0MS6_10_40"]]
    Yr0NS6_10_40 <- TDMdata[["Yr0NS6_10_40"]]
    Yr1MS6_10_40 <- TDMdata[["Yr1MS6_10_40"]]
    Yr1NS6_10_40 <- TDMdata[["Yr1NS6_10_40"]]
    Yr2MS6_10_40 <- TDMdata[["Yr2MS6_10_40"]]
    Yr2NS6_10_40 <- TDMdata[["Yr2NS6_10_40"]]
    Yr3MS6_10_40 <- TDMdata[["Yr3MS6_10_40"]]
    Yr3NS6_10_40 <- TDMdata[["Yr3NS6_10_40"]]
    Yr4MS6_10_40 <- TDMdata[["Yr4MS6_10_40"]]
    Yr4NS6_10_40 <- TDMdata[["Yr4NS6_10_40"]]
    NumDoses6_10_40 <- TDMdata[["NumDoses6_10_40"]]
    
    Yr0MS1_6_10 <- TDMdata[["Yr0MS1_6_10"]]
    Yr0NS1_6_10 <- TDMdata[["Yr0NS1_6_10"]]
    Yr1MS1_6_10 <- TDMdata[["Yr1MS1_6_10"]]
    Yr1NS1_6_10 <- TDMdata[["Yr1NS1_6_10"]]
    Yr2MS1_6_10 <- TDMdata[["Yr2MS1_6_10"]]
    Yr2NS1_6_10 <- TDMdata[["Yr2NS1_6_10"]]
    Yr3MS1_6_10 <- TDMdata[["Yr3MS1_6_10"]]
    Yr3NS1_6_10 <- TDMdata[["Yr3NS1_6_10"]]
    Yr4MS1_6_10 <- TDMdata[["Yr4MS1_6_10"]]
    Yr4NS1_6_10 <- TDMdata[["Yr4NS1_6_10"]]
    NumDoses1_6_10 <- TDMdata[["NumDoses1_6_10"]]
```

```{r}
for(i in 1:1000){
  set.seed(1+i)
### TDM outputs ###
  #Moderate-Severe Cases
  MSCases_NoVac =           as.numeric(Yr0MSNoVac[i,]+Yr1MSNoVac[i,]+Yr2MSNoVac[i,]+Yr3MSNoVac[i,]+Yr4MSNoVac[i,])
  MSCases_Rotarix6_10 =     as.numeric(Yr0MS6_10[i,]+Yr1MS6_10[i,]+Yr2MS6_10[i,]+Yr3MS6_10[i,]+Yr4MS6_10[i,])
  MSCases_Rotarix6_10_14 =  as.numeric(Yr0MS6_10_14[i,]+Yr1MS6_10_14[i,]+Yr2MS6_10_14[i,]+Yr3MS6_10_14[i,]+Yr4MS6_10_14[i,])
  MSCases_Rotarix6_10_40 =  as.numeric(Yr0MS6_10_40[i,]+Yr1MS6_10_40[i,]+Yr2MS6_10_40[i,]+Yr3MS6_10_40[i,]+Yr4MS6_10_40[i,])
  MSCases_Neonatal1_6_10 =  as.numeric(Yr0MS1_6_10[i,]+Yr1MS1_6_10[i,]+Yr2MS1_6_10[i,]+Yr3MS1_6_10[i,]+Yr4MS1_6_10[i,])
  
  #Non-Severe Cases
  NSCases_NoVac =           as.numeric(Yr0NSNoVac[i,]+Yr1NSNoVac[i,]+Yr2NSNoVac[i,]+Yr3NSNoVac[i,]+Yr4NSNoVac[i,])
  NSCases_Rotarix6_10 =     as.numeric(Yr0NS6_10[i,]+Yr1NS6_10[i,]+Yr2NS6_10[i,]+Yr3NS6_10[i,]+Yr4NS6_10[i,])
  NSCases_Rotarix6_10_14 =  as.numeric(Yr0NS6_10_14[i,]+Yr1NS6_10_14[i,]+Yr2NS6_10_14[i,]+Yr3NS6_10_14[i,]+Yr4NS6_10_14[i,])
  NSCases_Rotarix6_10_40 =  as.numeric(Yr0NS6_10_40[i,]+Yr1NS6_10_40[i,]+Yr2NS6_10_40[i,]+Yr3NS6_10_40[i,]+Yr4NS6_10_40[i,])
  NSCases_Neonatal1_6_10 =  as.numeric(Yr0NS1_6_10[i,]+Yr1NS1_6_10[i,]+Yr2NS1_6_10[i,]+Yr3NS1_6_10[i,]+Yr4NS1_6_10[i,])
  
  #Vax doses
  NumDoses_Rotarix6_10 =    as.numeric(NumDoses6_10[i,])
  NumDoses_Rotarix6_10_14 = as.numeric(NumDoses6_10_14[i,])
  NumDoses_Rotarix6_10_40 = as.numeric(NumDoses6_10_40[i,])
  NumDoses_Neonatal1_6_10 = as.numeric(NumDoses1_6_10[i,])

### Uncertainty Parameters ###
  pr_seek =  rbeta(1,2600.06,650.01)    # P of seeking treatment
  pr_no_treat =	1-pr_seek               # P of no treatment
  
  pr_inpat = rbeta(1,1432.08,954.72)    # P of inpatient (hospitalization)
  pr_outpat_MS = 1-pr_inpat             # P of outpatient treatment 

  pr_outpat_NS = rbeta(1,832.82,681.39) # P of outpatient treatment for nonsevere disease
  pr_no_treat_NS = 1-pr_outpat_NS       # P of no treatment for nonsevere disease
  
  life_exp = 63
  
  # CFR: Case Fatality Rate
  pr_death_inpat = rbeta(1,6.74,606.29)         # CFR for inpatients 
  pr_death_outpat =	runif(1,0,1)*pr_death_inpat # CFR for outpatients
  pr_death_notreat =	rbeta(1,6.63,258.72)      # CFR for those who don't seek treatment
 
  # Costs
  wastage = 0.05
  delRotarix = 0.58     # Delivery cost
  costRotarix = 1.94    # Cost of 1 dose of Rotarix
  costNeonatal = 1.32   # Cost of 1 dose of Neonatal vaccine
  cost_switching = c(1024365,0,0,0,0,0,0,0,0,0) 
  cost_vacc_Rotarix6_10 = costRotarix + delRotarix        # Rotarix6_10 vaccine costs per dose
  cost_vacc_Rotarix6_10_14 = costRotarix + delRotarix     # Rotarix6_10 vaccine costs per dose
  cost_vacc_Rotarix6_10_40 = costRotarix + delRotarix     # Rotarix6_10_40 vaccine costs per dose
  cost_vacc_Neonatal1_6_10 = costNeonatal + delRotarix    # Rotarix6_10 vaccine costs per dose
  
  # Cost of treatment (Government perspective)
  cost_out_trt_NS =         rgamma(1,7.56,scale=1.47)     # outpatient treatment costs nonsevere
  cost_in_trt =             rgamma(1,1.39,scale=43.54)    # inpatient treatment costs 
  cost_out_trt_MS =         rgamma(1,15.18,scale=1.46)    # outpatient treatment costs moderate-severe 
  
  ## Uncomment to run societal perspective
  # # Cost of treatment (Societal)
  # cost_out_trt_NS =         rgamma(1,7.56,scale=1.47) + rgamma(1,0.24,scale=2.87)      # outpatient treatment costs nonsevere
  # cost_in_trt =             rgamma(1,1.39,scale=43.54) + rgamma(1,0.81,scale=18.76)    # inpatient treatment costs
  # cost_out_trt_MS =         rgamma(1,15.18,scale=1.46) + rgamma(1,0.79,scale=11.94)   # outpatient treatment costs moderate-severe

  #DALYs
  daly_wt_NS = runif(1,0.133,0.299) # DALY weight nonsevere
  daly_wt_MS = runif(1,0.184,0.399) # DALY weight moderate-severe
  dur_inf = 6/365                   # duration of illness
  
  discount = 0.03 # discounting rate
  
  #Store parameters in params
  params$pr_seek[i] =                  pr_seek
  params$pr_no_treat[i] =              pr_no_treat
  params$pr_inpat[i] =                 pr_inpat
  params$pr_outpat_MS[i] =             pr_outpat_MS
  params$pr_outpat_NS[i] =             pr_outpat_NS
  params$pr_no_treat_NS[i] =           pr_no_treat_NS
  params$pr_death_inpat[i] =           pr_death_inpat
  params$pr_death_outpat[i] =          pr_death_outpat
  params$pr_death_notreat[i] =         pr_death_notreat
  params$delRotarix[i] =               delRotarix
  params$cost_vacc_Rotarix6_10[i] =    cost_vacc_Rotarix6_10
  params$cost_vacc_Rotarix6_10_14[i] = cost_vacc_Rotarix6_10_14
  params$cost_vacc_Rotarix6_10_40[i] = cost_vacc_Rotarix6_10_40
  params$cost_vacc_Neonatal1_6_10[i] = cost_vacc_Neonatal1_6_10
  params$cost_in_trt[i] =              cost_in_trt
  params$cost_out_trt_NS[i] =          cost_out_trt_NS
  params$cost_out_trt_MS[i] =          cost_out_trt_MS
  params$daly_wt_NS[i] =               daly_wt_NS
  params$daly_wt_MS[i] =               daly_wt_MS
  params$dur_inf[i] =                  dur_inf
  
  
#### No vaccination ####
for (j in 1:10){

# Save the output for simulation i
  # nonsevere cases + severe cases
  yearData[i,"NumCases_NoVac",j] <- NSCases_NoVac[j] + MSCases_NoVac[j]
  # P of seeking care * P of inpatient treatment * number M/S cases
  yearData[i,"NoVacHosp",j]      <- pr_seek*pr_inpat*MSCases_NoVac[j]
  # ( P of seeking care * P of inpatient treatment * P of inpatient death +
  # P of seeking care * P of outpatient treatment * P of outpatient death +
  # P of no treatment * P of death on no treatment ) * number M/S cases
  yearData[i,"NoVacDeaths",j]    <- (pr_seek*pr_inpat*pr_death_inpat +
                                   pr_seek*pr_outpat_MS*pr_death_outpat +
                                   pr_no_treat*pr_death_notreat)*MSCases_NoVac[j]

# Calculate Total Cost
  yearData[i,"NoVacCostInt",j] =   0
  # cost of inpatient treatment * number of hospitalizations
  # + mod/sev cost of outpatient treatment * number outpatient treated
  # + nonsevere cost of outpatient treatment * number outpatient treated
  yearData[i,"NoVacCostTrt",j] =   (cost_in_trt*yearData[i,"NoVacHosp",j] +
                                  (cost_out_trt_MS*pr_seek*pr_outpat_MS)*MSCases_NoVac[j] +
                                  (cost_out_trt_NS*pr_outpat_NS)*NSCases_NoVac[j])/((1+discount)^(j-1))
  yearData[i,"NoVacCost",j] = (yearData[i,"NoVacCostTrt",j] +
                              yearData[i,"NoVacCostInt",j])
# DALYs for No Vacc
  # (Number nonsevere cases * duration of infection * DALY weight for nonsevere cases
  # + Number mod/sev cases * duration of infection * DALY weight for mod/sev cases
  # + ( P of inpatient death + P of outpatient death + P of no treatment (death stratified by age))
  # * incidence * life expectancy) / discounting rate
  yearData[i,"NoVacDALYs",j] = (NSCases_NoVac[j]*dur_inf*daly_wt_NS +
                              MSCases_NoVac[j]*dur_inf*daly_wt_MS +
                              (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                              pr_no_treat*pr_death_notreat) *(Yr0MSNoVac[i,j]*(29.96876412))+
                              (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                              pr_no_treat*pr_death_notreat)*(Yr1MSNoVac[i,j]*(29.8134343))+
                              (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                              pr_no_treat*pr_death_notreat)*(Yr2MSNoVac[i,j]*(29.65344459))+
                              (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                              pr_no_treat*pr_death_notreat)*(Yr3MSNoVac[i,j]*(29.48865518))+
                              (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                              pr_no_treat*pr_death_notreat)*(Yr4MSNoVac[i,j]*(29.31892209))) /((1+discount)^(j-1))

#### Rotarix6_10 Vaccination ####

# Save the output for simulation i
  # nonsevere cases + severe cases
  yearData[i,"NumCases_Rotarix6_10",j] <- NSCases_Rotarix6_10[j] + MSCases_Rotarix6_10[j]
  # P of seeking care * P of inpatient treatment * number M/S cases
  yearData[i,"Rotarix6_10Hosp",j]      <- pr_seek*pr_inpat*MSCases_Rotarix6_10[j]
  # ( P of seeking care * P of inpatient treatment * P of inpatient death
  # P of seeking care * P of outpatient treatment * P of outpatient death
  # P of no treatment * P of death on no treatment ) * number M/S cases
  yearData[i,"Rotarix6_10Deaths",j]    <- (pr_seek*pr_inpat*pr_death_inpat +
                                         pr_seek*pr_outpat_MS*pr_death_outpat +
                                         (1-pr_seek)*pr_death_notreat)*MSCases_Rotarix6_10[j]


# Calculate Cost
  # (Cost of 1 dose * number of doses administered +
  # Vaccine Wastage) / discounting rate
  yearData[i,"Rotarix6_10CostInt",j] = (cost_vacc_Rotarix6_10*NumDoses_Rotarix6_10[j]
                                      +(wastage*costRotarix*NumDoses_Rotarix6_10[j]))/((1+discount)^(j-1))
  # (cost of inpatient treatment * number of hospitalizations
  # + mod/sev cost of outpatient treatment * n outpatient treated
  # + nonsevere cost of outpatient treatment * n outpatient treated) / discounting rate
  yearData[i,"Rotarix6_10CostTrt",j] = (cost_in_trt*yearData[i,"Rotarix6_10Hosp",j] +
                                      cost_out_trt_MS*pr_seek*pr_outpat_MS*MSCases_Rotarix6_10[j] + 
                                        cost_out_trt_NS*pr_outpat_NS*NSCases_Rotarix6_10[j])/((1+discount)^(j-1))
  
  yearData[i,"Rotarix6_10Cost",j] =   (yearData[i,"Rotarix6_10CostInt",j] +
                                      yearData[i,"Rotarix6_10CostTrt",j])

# DALYs for Rotarix6_10
  # (Number nonsevere cases * duration of infection * DALY weight for nonsevere cases
  # + Number mod/sev cases * duration of infection * DALY weight for mod/sev cases
  # + ( P of inpatient death + P of outpatient death + P of no treatment (death stratified by age))
  # * incidence * life expectancy) / discounting rate
  yearData[i,"Rotarix6_10DALYs",j] = (NSCases_Rotarix6_10[j]*dur_inf*daly_wt_NS +
                                      MSCases_Rotarix6_10[j]*dur_inf*daly_wt_MS + 
                                      (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                      pr_no_treat*pr_death_notreat)*(Yr0MS6_10[i,j]*(29.96876412))+
                                      (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                      pr_no_treat*pr_death_notreat)*(Yr1MS6_10[i,j]*(29.8134343))+
                                      (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                      pr_no_treat*pr_death_notreat)*(Yr2MS6_10[i,j]*(29.65344459))+
                                      (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                      pr_no_treat*pr_death_notreat)*(Yr3MS6_10[i,j]*(29.48865518))+
                                      (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                      pr_no_treat*pr_death_notreat)*(Yr4MS6_10[i,j]*(29.31892209))) /((1+discount)^(j-1))
#### Rotarix6_10_14 Vaccination ####

# Save the output for simulation i
  # nonsevere cases + severe cases
  yearData[i,"NumCases_Rotarix6_10_14",j] <- NSCases_Rotarix6_10_14[j] + MSCases_Rotarix6_10_14[j]
  # P seeking care * P of inpatient treatment * number M/S cases
  yearData[i,"Rotarix6_10_14Hosp",j]      <- pr_seek*pr_inpat*MSCases_Rotarix6_10_14[j]
  # (P seeking care * P inpatient treatment * P inpatient death
  # P seeking care * P outpatient treatment * P outpatient death
  # P no treatment * P death on no treatment ) * number M/S cases
  yearData[i,"Rotarix6_10_14Deaths",j]    <- (pr_seek*pr_inpat*pr_death_inpat +
                                            pr_seek*pr_outpat_MS*pr_death_outpat +
                                            (1-pr_seek)*pr_death_notreat)*MSCases_Rotarix6_10_14[j]


# Calculate Cost
  # (Cost of 1 dose * number of doses administered +
  # Vaccine Wastage) / discounting rate
  yearData[i,"Rotarix6_10_14CostInt",j] =  (cost_vacc_Rotarix6_10_14*NumDoses_Rotarix6_10_14[j]
                                          +(wastage*costRotarix*NumDoses_Rotarix6_10_14[j]))/((1+discount)^(j-1))
  # cost of inpatient treatment * number of hospitalizations
  # + MS cost of outpatient treatment * n outpatient treated
  # + NS cost of outpatient treatment * n outpatient treated / discount rate
  yearData[i,"Rotarix6_10_14CostTrt",j] = (cost_in_trt*yearData[i,"Rotarix6_10_14Hosp",j] +
                                          cost_out_trt_MS*pr_seek*pr_outpat_MS*MSCases_Rotarix6_10_14[j] +
                                          cost_out_trt_NS*pr_outpat_NS*NSCases_Rotarix6_10_14[j])/((1+discount)^(j-1))
  yearData[i,"Rotarix6_10_14Cost",j] =    (yearData[i,"Rotarix6_10_14CostInt",j] +
                                          yearData[i,"Rotarix6_10_14CostTrt",j])

# DALYs for Rotarix6_10_14
  # (Number nonsevere cases * duration of infection * DALY weight for nonsevere cases
  # + Number mod/sev cases * duration of infection * DALY weight for mod/sev cases
  # + ( P of inpatient death + P of outpatient death + P of no treatment (death stratified by age))
  # * incidence * life expectancy) / discounting rate
  yearData[i,"Rotarix6_10_14DALYs",j] =  (NSCases_Rotarix6_10_14[j]*dur_inf*daly_wt_NS +
                                        MSCases_Rotarix6_10_14[j]*dur_inf*daly_wt_MS +
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr0MS6_10_14[i,j]*(29.96876412))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr1MS6_10_14[i,j]*(29.8134343))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr2MS6_10_14[i,j]*(29.65344459))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr3MS6_10_14[i,j]*(29.48865518))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +                                                            pr_no_treat*pr_death_notreat)*(Yr4MS6_10_14[i,j]*(29.31892209))) /((1+discount)^(j-1))

#### Rotarix6_10_40 Vaccination ####
# Save the output for simulation i
  # nonsevere cases + severe cases
  yearData[i,"NumCases_Rotarix6_10_40",j] <- NSCases_Rotarix6_10_40[j] + MSCases_Rotarix6_10_40[j]
  # P seeking care * P inpatient treatment * number M/S cases
  yearData[i,"Rotarix6_10_40Hosp",j]      <- pr_seek*pr_inpat*MSCases_Rotarix6_10_40[j]
  # (P seeking care * P inpatient treatment * P inpatient death
  # P seeking care * P outpatient treatment * P outpatient death
  # P no treatment * P death on no treatment ) * number M/S cases
  yearData[i,"Rotarix6_10_40Deaths",j]    <- (pr_seek*pr_inpat*pr_death_inpat +
                                            pr_seek*pr_outpat_MS*pr_death_outpat +
                                            (1-pr_seek)*pr_death_notreat)*MSCases_Rotarix6_10_40[j]


# Calculate Cost
  # Cost of 1 dose * number of doses administered +
  # Vaccine wastage / discount rate
  yearData[i,"Rotarix6_10_40CostInt",j] = (cost_vacc_Rotarix6_10_40*NumDoses_Rotarix6_10_40[j]
                                          +(wastage*costRotarix*NumDoses_Rotarix6_10_40[j]))/((1+discount)^(j-1))
  # cost of inpatient treatment * number of hospitalizations
  # + MS cost of outpatient treatment * n outpatient treated
  # + NS cost of outpatient treatment * n outpatient treated / discount rate
  yearData[i,"Rotarix6_10_40CostTrt",j] = (cost_in_trt*yearData[i,"Rotarix6_10_40Hosp",j] +
                                          cost_out_trt_MS*pr_seek*pr_outpat_MS*MSCases_Rotarix6_10_40[j] +
                                          cost_out_trt_NS*pr_outpat_NS*NSCases_Rotarix6_10_40[j])/((1+discount)^(j-1))
  yearData[i,"Rotarix6_10_40Cost",j] =     (yearData[i,"Rotarix6_10_40CostInt",j] + yearData[i,"Rotarix6_10_40CostTrt",j])

# DALYs for Rotarix6_10_40
  # (Number nonsevere cases * duration of infection * DALY weight for nonsevere cases
  # + Number mod/sev cases * duration of infection * DALY weight for mod/sev cases
  # + ( P of inpatient death + P of outpatient death + P of no treatment (death stratified by age))
  # * incidence * life expectancy) / discounting rate
  yearData[i,"Rotarix6_10_40DALYs",j] =  (NSCases_Rotarix6_10_40[j]*dur_inf*daly_wt_NS +
                                        MSCases_Rotarix6_10_40[j]*dur_inf*daly_wt_MS +
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr0MS6_10_40[i,j]*(29.96876412))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr1MS6_10_40[i,j]*(29.8134343))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr2MS6_10_40[i,j]*(29.65344459))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr3MS6_10_40[i,j]*(29.48865518))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr4MS6_10_40[i,j]*(29.31892209))) /((1+discount)^(j-1))#

#### Neonatal1_6_10 Vaccination ####
# Save the output for simulation i
  # nonsevere cases + severe cases
  yearData[i,"NumCases_Neonatal1_6_10",j] <- NSCases_Neonatal1_6_10[j] + MSCases_Neonatal1_6_10[j]
  # P seeking care * P inpatient treatment * number M/S cases
  yearData[i,"Neonatal1_6_10Hosp",j]      <- pr_seek*pr_inpat*MSCases_Neonatal1_6_10[j]
  # ( P seeking care * P of inpatient treatment * P inpatient death
  # P seeking care * P outpatient treatment * P outpatient death
  # P no treatment * P death on no treatment ) * number M/S cases
  yearData[i,"Neonatal1_6_10Deaths",j]    <- (pr_seek*pr_inpat*pr_death_inpat +
                                         pr_seek*pr_outpat_MS*pr_death_outpat +
                                         (1-pr_seek)*pr_death_notreat)*MSCases_Neonatal1_6_10[j]

# Calculate Cost
  # Cost of 1 dose * number of doses administered + Cost of switching
  # + Vaccine wastage / discount rate
  yearData[i,"Neonatal1_6_10CostInt",j] = (cost_vacc_Neonatal1_6_10*NumDoses_Neonatal1_6_10[j] + cost_switching[j] +
                                          (wastage*costNeonatal*NumDoses_Neonatal1_6_10[j]))/((1+discount)^(j-1))
  # cost of inpatient treatment * n of hospitalizations
  # + MS cost of outpatient treatment * n outpatient treated
  # + NS cost of outpatient treatment * n outpatient treated / discounting rate
  yearData[i,"Neonatal1_6_10CostTrt",j] = (cost_in_trt*yearData[i,"Neonatal1_6_10Hosp",j] +
                                          cost_out_trt_MS*pr_seek*pr_outpat_MS*MSCases_Neonatal1_6_10[j] +
                                          cost_out_trt_NS*pr_outpat_NS*NSCases_Neonatal1_6_10[j])/((1+discount)^(j-1))
  yearData[i,"Neonatal1_6_10Cost",j] =    (yearData[i,"Neonatal1_6_10CostInt",j] +
                                          yearData[i,"Neonatal1_6_10CostTrt",j])

# DALYs for Neonatal1_6_10
  # (Number nonsevere cases * duration of infection * DALY weight for nonsevere cases
  # + Number mod/sev cases * duration of infection * DALY weight for mod/sev cases
  # + ( P of inpatient death + P of outpatient death + P of no treatment (death stratified by age))
  # * incidence * life expectancy) / discounting rate
  yearData[i,"Neonatal1_6_10DALYs",j] =  (NSCases_Neonatal1_6_10[j]*dur_inf*daly_wt_NS +
                                        MSCases_Neonatal1_6_10[j]*dur_inf*daly_wt_MS +
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr0MS1_6_10[i,j]*(29.96876412))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr1MS1_6_10[i,j]*(29.8134343))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr2MS1_6_10[i,j]*(29.65344459))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr3MS1_6_10[i,j]*(29.48865518))+
                                        (pr_inpat*pr_death_inpat + pr_outpat_MS*pr_death_outpat +
                                        pr_no_treat*pr_death_notreat)*(Yr4MS1_6_10[i,j]*(29.31892209))) /((1+discount)^(j-1))

  }

# Sum the yearly output data over ten years for each simulation
  outputArray$NumCases_NoVac[i] <- sum(yearData[i,"NumCases_NoVac",])
  outputArray$NumCases_Rotarix6_10[i] <- sum(yearData[i,"NumCases_Rotarix6_10",])
  outputArray$NumCases_Rotarix6_10_14[i] <- sum(yearData[i,"NumCases_Rotarix6_10_14",])
  outputArray$NumCases_Rotarix6_10_40[i] <- sum(yearData[i,"NumCases_Rotarix6_10_40",])
  outputArray$NumCases_Neonatal1_6_10[i] <- sum(yearData[i,"NumCases_Neonatal1_6_10",])
  outputArray$MSCases_NoVac[i] <- sum(MSCases_NoVac)
  outputArray$MSCases_Rotarix6_10[i] <- sum(MSCases_Rotarix6_10)
  outputArray$MSCases_Rotarix6_10_14[i] <- sum(MSCases_Rotarix6_10_14)
  outputArray$MSCases_Rotarix6_10_40[i] <- sum(MSCases_Rotarix6_10_40)
  outputArray$MSCases_Neonatal1_6_10[i] <- sum(MSCases_Neonatal1_6_10)
  outputArray$NSCases_NoVac[i] <- sum(NSCases_NoVac)
  outputArray$NSCases_Rotarix6_10[i] <- sum(NSCases_Rotarix6_10)
  outputArray$NSCases_Rotarix6_10_14[i] <- sum(NSCases_Rotarix6_10_14)
  outputArray$NSCases_Rotarix6_10_40[i] <- sum(NSCases_Rotarix6_10_40)
  outputArray$NSCases_Neonatal1_6_10[i] <- sum(NSCases_Neonatal1_6_10)
  outputArray$NoVacHosp[i] <- sum(yearData[i,"NoVacHosp",])
  outputArray$Rotarix6_10Hosp[i] <- sum(yearData[i,"Rotarix6_10Hosp",])
  outputArray$Rotarix6_10_14Hosp[i] <- sum(yearData[i,"Rotarix6_10_14Hosp",])
  outputArray$Rotarix6_10_40Hosp[i] <- sum(yearData[i,"Rotarix6_10_40Hosp",])
  outputArray$Neonatal1_6_10Hosp[i] <- sum(yearData[i,"Neonatal1_6_10Hosp",])
  outputArray$NoVacDeaths[i] <- sum(yearData[i,"NoVacDeaths",])
  outputArray$Rotarix6_10Deaths[i] <- sum(yearData[i,"Rotarix6_10Deaths",])
  outputArray$Rotarix6_10_14Deaths[i] <- sum(yearData[i,"Rotarix6_10_14Deaths",])
  outputArray$Rotarix6_10_40Deaths[i] <- sum(yearData[i,"Rotarix6_10_40Deaths",])
  outputArray$Neonatal1_6_10Deaths[i] <- sum(yearData[i,"Neonatal1_6_10Deaths",])
  outputArray$NoVacCost[i] <- sum(yearData[i,"NoVacCost",])
  outputArray$Rotarix6_10Cost[i] <- sum(yearData[i,"Rotarix6_10Cost",])
  outputArray$Rotarix6_10_14Cost[i] <- sum(yearData[i,"Rotarix6_10_14Cost",])
  outputArray$Rotarix6_10_40Cost[i] <- sum(yearData[i,"Rotarix6_10_40Cost",])
  outputArray$Neonatal1_6_10Cost[i] <- sum(yearData[i,"Neonatal1_6_10Cost",])
  outputArray$NoVacCostInt[i] <- sum(yearData[i,"NoVacCostInt",])
  outputArray$Rotarix6_10CostInt[i] <- sum(yearData[i,"Rotarix6_10CostInt",])
  outputArray$Rotarix6_10_14CostInt[i] <- sum(yearData[i,"Rotarix6_10_14CostInt",])
  outputArray$Rotarix6_10_40CostInt[i] <- sum(yearData[i,"Rotarix6_10_40CostInt",])
  outputArray$Neonatal1_6_10CostInt[i] <- sum(yearData[i,"Neonatal1_6_10CostInt",])
  outputArray$NoVacCostTrt[i] <- sum(yearData[i,"NoVacCostTrt",])
  outputArray$Rotarix6_10CostTrt[i] <- sum(yearData[i,"Rotarix6_10CostTrt",])
  outputArray$Rotarix6_10_14CostTrt[i] <- sum(yearData[i,"Rotarix6_10_14CostTrt",])
  outputArray$Rotarix6_10_40CostTrt[i] <- sum(yearData[i,"Rotarix6_10_40CostTrt",])
  outputArray$Neonatal1_6_10CostTrt[i] <- sum(yearData[i,"Neonatal1_6_10CostTrt",])
  outputArray$NoVacDALYs[i] <- sum(yearData[i,"NoVacDALYs",])
  outputArray$Rotarix6_10DALYs[i] <- sum(yearData[i,"Rotarix6_10DALYs",])
  outputArray$Rotarix6_10_14DALYs[i] <- sum(yearData[i,"Rotarix6_10_14DALYs",])
  outputArray$Rotarix6_10_40DALYs[i] <- sum(yearData[i,"Rotarix6_10_40DALYs",])
  outputArray$Neonatal1_6_10DALYs[i] <- sum(yearData[i,"Neonatal1_6_10DALYs",])

# calculate CE Ratios - each strategy compared to 6/10 for plotting PSA in CEA Plane
  outputArray$CERatioY_NoVac[i] = (outputArray$NoVacCost[i]-outputArray$Rotarix6_10Cost[i])
  outputArray$CERatioX_NoVac[i] = (outputArray$Rotarix6_10DALYs[i]-outputArray$NoVacDALYs[i])
  outputArray$CERatioY_Rotarix6_10_14[i] = (outputArray$Rotarix6_10_14Cost[i]-outputArray$Rotarix6_10Cost[i])
  outputArray$CERatioX_Rotarix6_10_14[i] = (outputArray$Rotarix6_10DALYs[i]-outputArray$Rotarix6_10_14DALYs[i])
  outputArray$CERatioY_Rotarix6_10_40[i] = (outputArray$Rotarix6_10_40Cost[i]-outputArray$Rotarix6_10Cost[i])
  outputArray$CERatioX_Rotarix6_10_40[i] = (outputArray$Rotarix6_10DALYs[i]-outputArray$Rotarix6_10_40DALYs[i])
  outputArray$CERatioY_Neonatal1_6_10[i] = (outputArray$Neonatal1_6_10Cost[i]-outputArray$Rotarix6_10Cost[i])
  outputArray$CERatioX_Neonatal1_6_10[i] = (outputArray$Rotarix6_10DALYs[i]-outputArray$Neonatal1_6_10DALYs[i])

# Calculate ICERs ( Commented out = dominated )
  outputArray$ICERatio_Neonatal1_6_10[i] = (outputArray$Neonatal1_6_10Cost[i]-outputArray$NoVacCost[i])/                                                                                                                  (outputArray$NoVacDALYs[i]-outputArray$Neonatal1_6_10DALYs[i])
  outputArray$ICERatio_Rotarix6_10_14[i] = (outputArray$Rotarix6_10_14Cost[i]-outputArray$Neonatal1_6_10Cost[i])/
                                           (outputArray$Neonatal1_6_10DALYs[i]-outputArray$Rotarix6_10_14DALYs[i])
  outputArray$ICERatio_Rotarix6_10[i] =    (outputArray$Rotarix6_10Cost[i]-outputArray$Neonatal1_6_10Cost[i])/
                                           (outputArray$Neonatal1_6_10DALYs[i]-outputArray$Rotarix6_10DALYs[i])
  outputArray$ICERatio_Rotarix6_10_40[i] = (outputArray$Rotarix6_10_40Cost[i]-outputArray$Rotarix6_10_14Cost[i])/
                                           (outputArray$Rotarix6_10_14DALYs[i]-outputArray$Rotarix6_10_40DALYs[i])

  }

# Calculate Cases Averted, Hosp Averted, Deaths Averted
# Nonsevere Cases
NSCasesAverted_Rotarix6_10    <- NSCases_Rotarix6_10-NSCases_NoVac
NSCasesAverted_Rotarix6_10_14 <- NSCases_Rotarix6_10-NSCases_Rotarix6_10_14
NSCasesAverted_Rotarix6_10_40 <- NSCases_Rotarix6_10-NSCases_Rotarix6_10_40
NSCasesAverted_Neonatal1_6_10 <- NSCases_Rotarix6_10-NSCases_Neonatal1_6_10
# Moderate-Severe Cases
MSCasesAverted_Rotarix6_10    <- MSCases_Rotarix6_10-MSCases_NoVac
MSCasesAverted_Rotarix6_10_14 <- MSCases_Rotarix6_10-MSCases_Rotarix6_10_14
MSCasesAverted_Rotarix6_10_40 <- MSCases_Rotarix6_10-MSCases_Rotarix6_10_40
MSCasesAverted_Neonatal1_6_10 <- MSCases_Rotarix6_10-MSCases_Neonatal1_6_10

# Total Cases
outputArray$CasesAverted_NoVac          <- outputArray$NumCases_Rotarix6_10 - outputArray$NumCases_NoVac
outputArray$CasesAverted_Rotarix6_10_14 <- outputArray$NumCases_Rotarix6_10 - outputArray$NumCases_Rotarix6_10_14
outputArray$CasesAverted_Rotarix6_10_40 <- outputArray$NumCases_Rotarix6_10 - outputArray$NumCases_Rotarix6_10_40
outputArray$CasesAverted_Neonatal1_6_10 <- outputArray$NumCases_Rotarix6_10 - outputArray$NumCases_Neonatal1_6_10
# Total Hospitalizations
outputArray$HospAverted_NoVac           <- outputArray$Rotarix6_10Hosp - outputArray$NoVacHosp
outputArray$HospAverted_Rotarix6_10_14  <- outputArray$Rotarix6_10Hosp - outputArray$Rotarix6_10_14Hosp
outputArray$HospAverted_Rotarix6_10_40  <- outputArray$Rotarix6_10Hosp - outputArray$Rotarix6_10_40Hosp
outputArray$HospAverted_Neonatal1_6_10  <- outputArray$Rotarix6_10Hosp - outputArray$Neonatal1_6_10Hosp
# Total Deaths
outputArray$DeathsAverted_NoVac          <- outputArray$Rotarix6_10Deaths - outputArray$NoVacDeaths
outputArray$DeathsAverted_Rotarix6_10_14 <- outputArray$Rotarix6_10Deaths - outputArray$Rotarix6_10_14Deaths
outputArray$DeathsAverted_Rotarix6_10_40 <- outputArray$Rotarix6_10Deaths - outputArray$Rotarix6_10_40Deaths
outputArray$DeathsAverted_Neonatal1_6_10 <- outputArray$Rotarix6_10Deaths - outputArray$Neonatal1_6_10Deaths
# Total DALYs
outputArray$DALYsAverted_NoVac          <- outputArray$Rotarix6_10DALYs - outputArray$NoVacDALYs
outputArray$DALYsAverted_Rotarix6_10_14 <- outputArray$Rotarix6_10DALYs - outputArray$Rotarix6_10_14DALYs
outputArray$DALYsAverted_Rotarix6_10_40 <- outputArray$Rotarix6_10DALYs - outputArray$Rotarix6_10_40DALYs
outputArray$DALYsAverted_Neonatal1_6_10 <- outputArray$Rotarix6_10DALYs - outputArray$Neonatal1_6_10DALYs

```

## Net Monitary Benefit

```{r}
##  Net monetary benefit = (E * WTP) - C
##  E = effectiveness; WTP = willingness-to-pay threshold; C = cost 
##  E = DALYs of no vaccine - DALYs of vaccination strategy
##  Cost = Cost of vaccination strategy - cost of no vaccination
##  Cost-effectiveness acceptability curves

WTP <- seq(0,1000,10) # Define a vector of willingness-to-pay values

# Initialize matrices to save net benefit values for each strategy for number of simulations x number of WTP values
NB_NoVac <- matrix(data=NA,nrow=nsim,ncol=length(WTP))
NB_Rotarix6_10 <-matrix(data=NA,nrow=nsim,ncol=length(WTP))
NB_Rotarix6_10_14 <-matrix(data=NA,nrow=nsim,ncol=length(WTP))
NB_Rotarix6_10_40 <-matrix(data=NA,nrow=nsim,ncol=length(WTP))
NB_Neonatal1_6_10 <-matrix(data=NA,nrow=nsim,ncol=length(WTP))
P_NB <-matrix(data=NA,nrow=nsim,ncol=length(WTP))

for (i in 1:nsim) {
  for (j in 1:length(WTP)) {
    
    # Calculate net monetary benefit of each strategy (compared to no vaccination)
    NB_Rotarix6_10[i,j] <- 0
    NB_NoVac[i,j] <-  ((outputArray$Rotarix6_10DALYs[i]-
                        outputArray$NoVacDALYs[i])*WTP[j])-
                        (outputArray$NoVacCost[i]
                        -outputArray$Rotarix6_10Cost[i])
    NB_Rotarix6_10_14[i,j] <-  ((outputArray$Rotarix6_10DALYs[i]-
                        outputArray$Rotarix6_10_14DALYs[i])*WTP[j])-
                        (outputArray$Rotarix6_10_14Cost[i]
                        -outputArray$Rotarix6_10Cost[i])
    NB_Rotarix6_10_40[i,j] <- ((outputArray$Rotarix6_10DALYs[i]-
                        outputArray$Rotarix6_10_40DALYs[i])*WTP[j])-
                        (outputArray$Rotarix6_10_40Cost[i]-
                        outputArray$Rotarix6_10Cost[i])
    NB_Neonatal1_6_10[i,j] <- ((outputArray$Rotarix6_10DALYs[i]-
                        outputArray$Neonatal1_6_10DALYs[i])*WTP[j])-
                        (outputArray$Neonatal1_6_10Cost[i]-
                        outputArray$Rotarix6_10Cost[i])
    
    # Identify the preferred strategy (strategy with the highest net benefit) (1=no vaccination, 2=Rotarix6_10, 3=Rotarix6_10_14, 4=Rotarix6_10_40 5=Neonatal1_6_10)
   if(NB_NoVac[i,j]>NB_Rotarix6_10[i,j]&NB_NoVac[i,j]>NB_Rotarix6_10_14[i,j]&NB_NoVac[i,j]>NB_Rotarix6_10_40[i,j]&NB_NoVac[i,j]>NB_Neonatal1_6_10[i,j])
      {P_NB[i,j] <- 1}
    else if(NB_Rotarix6_10[i,j]>NB_NoVac[i,j]&NB_Rotarix6_10[i,j]>NB_Rotarix6_10_14[i,j]&NB_Rotarix6_10[i,j]>NB_Rotarix6_10_40[i,j]&NB_Rotarix6_10[i,j]>NB_Neonatal1_6_10[i,j])
      {P_NB[i,j] <- 2}
     else if(NB_Rotarix6_10_14[i,j]>NB_NoVac[i,j]&NB_Rotarix6_10_14[i,j]>NB_Rotarix6_10[i,j]&NB_Rotarix6_10_14[i,j]>NB_Rotarix6_10_40[i,j]&NB_Rotarix6_10_14[i,j]>NB_Neonatal1_6_10[i,j])
          {P_NB[i,j] <- 3}
    else if(NB_Rotarix6_10_40[i,j]>NB_NoVac[i,j]&NB_Rotarix6_10_40[i,j]>NB_Rotarix6_10[i,j]&NB_Rotarix6_10_40[i,j]>NB_Rotarix6_10_14[i,j]&NB_Rotarix6_10_40[i,j]>NB_Neonatal1_6_10[i,j])
      {P_NB[i,j] <- 4}
    else if(NB_Neonatal1_6_10[i,j]>NB_NoVac[i,j]&NB_Neonatal1_6_10[i,j]>NB_Rotarix6_10[i,j]&NB_Neonatal1_6_10[i,j]>NB_Rotarix6_10_14[i,j]&NB_Neonatal1_6_10[i,j]>NB_Rotarix6_10_40[i,j])
      {P_NB[i,j] <- 5}
  }
}

# Initialize vectors for the P each strategy results in the highest net benefit for each WTP value
P_NB_NoVac <- rep(0,length(WTP))
P_NB_Rotarix6_10 <- rep(0,length(WTP))
P_NB_Rotarix6_10_14 <- rep(0,length(WTP))
P_NB_Rotarix6_10_40 <- rep(0,length(WTP))
P_NB_Neonatal1_6_10 <- rep(0,length(WTP))

# Calculate the P each strategy results in the highest net benefit for each WTP value
for (j in 1:length(WTP)) {
  P_NB_NoVac[j] <- sum(P_NB[,j]==1)/nsim
  P_NB_Rotarix6_10[j] <- sum(P_NB[,j]==2)/nsim
  P_NB_Rotarix6_10_14[j] <- sum(P_NB[,j]==3)/nsim
  P_NB_Rotarix6_10_40[j] <- sum(P_NB[,j]==4)/nsim
  P_NB_Neonatal1_6_10[j] <- sum(P_NB[,j]==5)/nsim
}

### Cost-effectiveness acceptability frontier (CEAF)
# Initialize vectors net benefit values for each strategy for number of WTP values
NB_NoVac_mean <- c()
NB_Rotarix6_10_mean <- c()
NB_Rotarix6_10_14_mean <- c()
NB_Rotarix6_10_40_mean <- c()
NB_Neonatal1_6_10_mean <- c()
P_NB_mean <- c()

# Initialize vectors with "NA"s for CEAF curves
CEAF_NoVac <- rep(NA,length(WTP))
CEAF_Rotarix6_10 <- rep(NA,length(WTP))
CEAF_Rotarix6_10_14 <- rep(NA,length(WTP))
CEAF_Rotarix6_10_40 <- rep(NA,length(WTP))
CEAF_Neonatal1_6_10 <- rep(NA,length(WTP))

# Calculate the average net benefit and the P each strategy results is the highest avg net benefit for each WTP value
for (j in 1:length(WTP)) {
    
    NB_NoVac_mean[j] <- mean(NB_NoVac[,j])
    NB_Rotarix6_10_mean[j] <- mean(NB_Rotarix6_10[,j])
    NB_Rotarix6_10_14_mean[j] <- mean(NB_Rotarix6_10_14[,j])
    NB_Rotarix6_10_40_mean[j] <- mean(NB_Rotarix6_10_40[,j])
    NB_Neonatal1_6_10_mean[j] <- mean(NB_Neonatal1_6_10[,j])
    
    if(NB_NoVac_mean[j]>NB_Rotarix6_10_mean[j]&NB_NoVac_mean[j]>NB_Rotarix6_10_14_mean[j]&NB_NoVac_mean[j]>NB_Rotarix6_10_40_mean[j]&NB_NoVac_mean[j]>NB_Neonatal1_6_10_mean[j]){
      P_NB_mean[j] <- 1
      CEAF_NoVac[j] <- P_NB_NoVac[j] # If No Vaccination is the preferred strategy, save the P it is preferred
    }
    else if(NB_Rotarix6_10_mean[j]>NB_NoVac_mean[j]&NB_Rotarix6_10_mean[j]>NB_Rotarix6_10_14_mean[j]&NB_Rotarix6_10_mean[j]>NB_Rotarix6_10_40_mean[j]&NB_Rotarix6_10_mean[j]>NB_Neonatal1_6_10_mean[j]){
      P_NB_mean[j] <- 2
      CEAF_Rotarix6_10[j] <- P_NB_Rotarix6_10[j]# If Rotarix6_10 is the preferred strategy, save the P it is preferred
    }
    else if(NB_Rotarix6_10_14_mean[j]>NB_NoVac_mean[j]&NB_Rotarix6_10_14_mean[j]>NB_Rotarix6_10_mean[j]&NB_Rotarix6_10_14_mean[j]>NB_Rotarix6_10_40_mean[j]&NB_Rotarix6_10_14_mean[j]>NB_Neonatal1_6_10_mean[j]){
      P_NB_mean[j] <- 3
      CEAF_Rotarix6_10_14[j] <- P_NB_Rotarix6_10_14[j]# If Rotarix6_10_14 is the preferred strategy, save the P it is preferred
    }
    else if(NB_Rotarix6_10_40_mean[j]>NB_NoVac_mean[j]&NB_Rotarix6_10_40_mean[j]>NB_Rotarix6_10_mean[j]&NB_Rotarix6_10_40_mean[j]>NB_Rotarix6_10_14_mean[j]&NB_Rotarix6_10_40_mean[j]>NB_Neonatal1_6_10_mean[j]){
      P_NB_mean[j] <- 4
      CEAF_Rotarix6_10_40[j] <- P_NB_Rotarix6_10_40[j]# If Rotarix6_10_40 is the preferred strategy, save the P it is preferred
    }
    else if(NB_Neonatal1_6_10_mean[j]>NB_NoVac_mean[j]&NB_Neonatal1_6_10_mean[j]>NB_Rotarix6_10_mean[j]&NB_Neonatal1_6_10_mean[j]>NB_Rotarix6_10_14_mean[j]&NB_Neonatal1_6_10_mean[j]>NB_Rotarix6_10_40_mean[j]){
      P_NB_mean[j] <- 5
      CEAF_Neonatal1_6_10[j] <- P_NB_Neonatal1_6_10[j]# If Neonatal1_6_10 is the preferred strategy, save the P it is preferred
    }
}
```

## CEAC

```{r}
# Plot the results
png('~/CEACP.png')
plot(WTP, P_NB_NoVac, type= "l", col='black', ylab="Probability of being cost-effective",xlab="WTP",
    main="Cost-Effectiveness Accesptability Curve\nAll Vaccine Strategies", ylim=c(0,1))
lines(WTP, P_NB_Rotarix6_10, col='#CA0020')
lines(WTP, P_NB_Rotarix6_10_14, col='#006BA4FF')
lines(WTP, P_NB_Rotarix6_10_40, col='#ABABABFF')
lines(WTP, P_NB_Neonatal1_6_10, col='#FF800EFF')
abline(v=335,col="darkgreen")
text(x=320, y=0.5, srt=90,col="darkgreen", cex=0.75, 'WTP (US $335)')
legend("bottomright",legend=c("No vaccination","Rotarix6_10","Rotarix6_10_14","Rotarix6_10_40","Neonatal1_6_10"),
      col=c("#595959FF","#CA0020","#006BA4FF","#ABABABFF","#FF800EFF"),
      lty=1, ncol=1, cex =.7, pt.cex = 1)

dev.off()

```

## CEAF

```{r}
# Plot the results
png('~/CEAFP.png')
plot(WTP, CEAF_NoVac, type= "b", col='black', ylab="Probability of having highest net benefit",xlab="WTP",
    main="Cost-Effectiveness Accesptability Frontier\nAll Vaccine Strategies", ylim=c(0,1))
lines(WTP,CEAF_NoVac, col='black')
lines(WTP, CEAF_Rotarix6_10, col='#CA0020')
lines(WTP, CEAF_Rotarix6_10_14, col='#006BA4FF')
lines(WTP, CEAF_Rotarix6_10_40, col='#ABABABFF')
lines(WTP, CEAF_Neonatal1_6_10, col='#FF800EFF')
points(WTP, CEAF_Rotarix6_10, col='#CA0020')
points(WTP, CEAF_Rotarix6_10_14, col='#006BA4FF')
points(WTP, CEAF_Rotarix6_10_40, col='#ABABABFF')
points(WTP, CEAF_Neonatal1_6_10, col='#FF800EFF')
abline(v=335,col="darkgreen")
text(x=320, y=0.5, srt=90,col="darkgreen", cex=0.75, 'WTP (US $335)')
legend("bottomright",legend=c("No Vaccination","Rotarix6_10 vaccination","Rotarix6_10_14 vaccination","Rotarix6_10_40 vaccination","Neonatal1_6_10 vaccination"),
      col=c("#595959FF","#CA0020","#006BA4FF","#ABABABFF","#FF800EFF"),
      lty=1, ncol=1, cex =.7, pt.cex = 1)
dev.off()
```

## ICERs

```{r}
## AVERAGE METRICS FOR ALL SIMULATIONS

#total cost
TotCost_NoVac          <- mean(outputArray$NoVacCost)
TotCost_Rotarix6_10    <- mean(outputArray$Rotarix6_10Cost)
TotCost_Rotarix6_10_14 <- mean(outputArray$Rotarix6_10_14Cost)
TotCost_Rotarix6_10_40 <- mean(outputArray$Rotarix6_10_40Cost)
TotCost_Neonatal1_6_10 <- mean(outputArray$Neonatal1_6_10Cost)
#intervention cost
IntCost_NoVac          <- mean(outputArray$NoVacCostInt)
IntCost_Rotarix6_10    <- mean(outputArray$Rotarix6_10CostInt)
IntCost_Rotarix6_10_14 <- mean(outputArray$Rotarix6_10_14CostInt)
IntCost_Rotarix6_10_40 <- mean(outputArray$Rotarix6_10_40CostInt)
IntCost_Neonatal1_6_10 <- mean(outputArray$Neonatal1_6_10CostInt)
#treatment cost
TrtCost_NoVac          <- mean(outputArray$NoVacCostTrt)
TrtCost_Rotarix6_10    <- mean(outputArray$Rotarix6_10CostTrt)
TrtCost_Rotarix6_10_14 <- mean(outputArray$Rotarix6_10_14CostTrt)
TrtCost_Rotarix6_10_40 <- mean(outputArray$Rotarix6_10_40CostTrt)
TrtCost_Neonatal1_6_10 <- mean(outputArray$Neonatal1_6_10CostTrt)
#dalys
DALYs_NoVac          <- mean(outputArray$NoVacDALYs)
DALYs_Rotarix6_10    <- mean(outputArray$Rotarix6_10DALYs)
DALYs_Rotarix6_10_14 <- mean(outputArray$Rotarix6_10_14DALYs)
DALYs_Rotarix6_10_40 <- mean(outputArray$Rotarix6_10_40DALYs)
DALYs_Neonatal1_6_10 <- mean(outputArray$Neonatal1_6_10DALYs)

#cost difference
costDiffNoVac   <- TotCost_NoVac - TotCost_Rotarix6_10
costDiff6_10_14 <- TotCost_Rotarix6_10_14 - TotCost_Rotarix6_10
costDiff6_10_40 <- TotCost_Rotarix6_10_40 - TotCost_Rotarix6_10
costDiff1_6_10  <- TotCost_Neonatal1_6_10 - TotCost_Rotarix6_10

#average outcomes averted
CasesavNV   <- mean(outputArray$CasesAverted_NoVac)
Casesav14   <- mean(outputArray$CasesAverted_Rotarix6_10_14)
Casesav40   <- mean(outputArray$CasesAverted_Rotarix6_10_40)
CasesavN10  <- mean(outputArray$CasesAverted_Neonatal1_6_10)
HospsavNV   <- mean(outputArray$HospAverted_NoVac)
Hospsav14   <- mean(outputArray$HospAverted_Rotarix6_10_14)
Hospsav40   <- mean(outputArray$HospAverted_Rotarix6_10_40)
HospsavN10  <- mean(outputArray$HospAverted_Neonatal1_6_10)
DALYsavNV   <- mean(outputArray$DALYsAverted_NoVac)
DALYsav14   <- mean(outputArray$DALYsAverted_Rotarix6_10_14)
DALYsav40   <- mean(outputArray$DALYsAverted_Rotarix6_10_40)
DALYsavN10  <- mean(outputArray$DALYsAverted_Neonatal1_6_10)
DeathsavNV  <- mean(outputArray$DeathsAverted_NoVac)
Deathsav14  <- mean(outputArray$DeathsAverted_Rotarix6_10_14)
Deathsav40  <- mean(outputArray$DeathsAverted_Rotarix6_10_40)
DeathsavN10 <- mean(outputArray$DeathsAverted_Neonatal1_6_10)
#costs per outcome averted
costCaseAvNV        <- costDiffNoVac/CasesavNV
costCaseAv6_10_14   <- costDiff6_10_14/Casesav14
costCaseAv6_10_40   <- costDiff6_10_40/Casesav40
costCaseAv1_6_10    <- costDiff1_6_10/CasesavN10
costHospAvNV        <- costDiffNoVac/HospsavNV
costHospAv6_10_14   <- costDiff6_10_14/Hospsav14
costHospAv6_10_40   <- costDiff6_10_40/Hospsav40
costHospAv1_6_10    <- costDiff1_6_10/HospsavN10
costDALYAvNV        <- costDiffNoVac/DALYsavNV
costDALYAv6_10_14   <- costDiff6_10_14/DALYsav14
costDALYAv6_10_40   <- costDiff6_10_40/DALYsav40
costDALYAv1_6_10    <- costDiff1_6_10/DALYsavN10
costDeathAvNV       <- costDiffNoVac/DeathsavNV
costDeathAv6_10_14  <- costDiff6_10_14/Deathsav14
costDeathAv6_10_40  <- costDiff6_10_40/Deathsav40
costDeathAv1_6_10   <- costDiff1_6_10/DeathsavN10


x <- c(outputArray$CERatioX_NoVac,outputArray$CERatioX_Rotarix6_10_14,
       outputArray$CERatioX_Rotarix6_10_40,outputArray$CERatioX_Neonatal1_6_10)
y <- c(outputArray$CERatioY_NoVac,outputArray$CERatioY_Rotarix6_10_14,
       outputArray$CERatioY_Rotarix6_10_40,outputArray$CERatioY_Neonatal1_6_10)
Strategy <- c(rep("No Vaccination",length(outputArray$CERatioX_NoVac)),
              rep("Rotarix 6/10/14",length(outputArray$CERatioX_NoVac)),
              rep("Rotarix 6/10/40",length(outputArray$CERatioX_NoVac)),
              rep("Neonatal 1/6/10",length(outputArray$CERatioX_NoVac)))
data1 <- data.frame(x,y,Strategy)

manual_points <- data.frame(
  x = c(DALYsavNV,DALYsav14,DALYsavN10),  # x-coordinates of the points
  y = c(costDiffNoVac,costDiff6_10_14,costDiff1_6_10),  # y-coordinates of the points
  label = c(print(round(costDALYAvNV,2)),print(round(costDALYAv6_10_14,2)),"Cost-saving"),  # Labels for the points
  col = c("black", "royalblue4","orangered")  # Colors for the points
)
manual_points1 <- data.frame(
  x = c(DALYsav40),  # x-coordinates of the points
  y = c(costDiff6_10_40),  # y-coordinates of the points
  label = c(print(round(costDALYAv6_10_40,2))),  # Labels for the points
  col = c("gray34")  # Colors for the points
)

ggplot(data1,aes(x,y,col=Strategy)) + 
  ggtitle("Cost-Effectiveness Plane", subtitle="Government Perspective - Strategies Compared to Rotarix 6/10") + 
  geom_point(size=0.5) + geom_textabline(slope=335, color="darkgreen",label="WTP Threshold") + 
  xlab("Difference in Effects of Vaccine Strategy (DALYs Averted)") + ylab("Difference in Cost of Vaccine Strategy") + 
  geom_hline(yintercept=0, color = "black") + geom_vline(xintercept=0, color = "black") + 
  scale_x_continuous(labels = unit_format(unit = "K", scale = 1e-3)) + 
  scale_y_continuous(labels = unit_format(unit = "K", scale = 1e-3)) + 
  theme(axis.text.y = element_text(angle = 90, hjust = 0.5)) +
  scale_color_manual(values = c("#FF800EFF","#595959FF","#006BA4FF","#ABABABFF")) + 
  # Add manual points with different colors
  geom_point(data = manual_points, aes(x = x, y = y), color = manual_points$col, size = 3) +
  geom_text(data = manual_points, aes(x = x, y = y, label = label), vjust = 1, hjust = -0.25, size = 4, fontface="bold", color = "black") +
  geom_point(data = manual_points1, aes(x = x, y = y), color = manual_points1$col, size = 3) +
  geom_text(data = manual_points1, aes(x = x, y = y, label = label), vjust = -1, hjust = 1.5, size = 4, fontface="bold", color = "black") +
  # geom_text(data = manual_points, aes(x = x, y = y, label = label), vjust = -1, size = 3) + 
  guides(colour = guide_legend(override.aes = list(size = 3))) + 
  theme(legend.title = element_text( size=10, face="bold"),legend.text = element_text(size=10,face="bold")) 
# +xlim(c(-60000000,40000000))+ylim(c(-60000000,40000000))

ggsave("CEAplane_plot3P.png", path ="~")

# code for % in Q3
mat <- rbind(outputArray$CERatioX_Neonatal1_6_10,outputArray$CERatioY_Neonatal1_6_10)
mat <- t(mat)
count <- 0
for (i in 1:1000){ if(mat[i,2]<0){count <- count+1}}
count/1000
# # [1] 0.793

```

## Violin Plots
```{r}
library(datasets)
library(ggplot2)
library(tidyr)
library(dplyr)
library(patchwork)
Labels <- c("No Vax","1/6/10","6/10","6/10/14", "6/10/40")

NewOA <- outputArray[,1:5] %>%
  mutate(across(everything(), ~ . / 1e6)) %>%
  pivot_longer(
    cols = everything(),     # Include all columns
    names_to = "Variable",   # New column for variable names
    values_to = "Value"      # New column for the values
  ) %>%
  group_by(Variable) %>%
  mutate(paired = seq_len(n())) %>% # Use seq_len(n()) to avoid potential issues with length
  ungroup() %>%
  mutate(
    Variable = factor(Variable, levels = c(
      "NumCases_NoVac",
      "NumCases_Neonatal1_6_10",
      "NumCases_Rotarix6_10",
      "NumCases_Rotarix6_10_14",
      "NumCases_Rotarix6_10_40"
    )) # Explicitly set the order
  )

cases <- ggplot(data = NewOA,
            mapping = aes(x = Variable, y = Value, fill = Variable)) +
            ggtitle("Cases") +
            geom_line(mapping = aes(group = paired), 
                      position = position_dodge(0.1), 
                      alpha = 0.1,   # Increase transparency for lines
                      color = "grey46", # Set a lighter color for the lines
                      linewidth = 0.25 # Use a thinner line
                      ) +
            geom_violin() +
            geom_point(mapping = aes(fill = Variable, group = paired),
                       size = 0.25, shape = 21,
                       position = position_dodge(0.1)) +
            scale_fill_manual(
              values = c(
                "NumCases_NoVac" = "#595959FF",      # Blue
                "NumCases_Neonatal1_6_10" = "#FF800EFF",
                "NumCases_Rotarix6_10" = "#CA0020", # Green
                "NumCases_Rotarix6_10_14" = "#006BA4FF", # Red
                "NumCases_Rotarix6_10_40" = "#ABABABFF"  # Purple
              )
            ) +
            scale_x_discrete(labels = Labels) + scale_y_continuous(limits = c(5,15)) +
              theme_classic() + xlab(NULL) + ylab("Cases (millions)") +
               theme(axis.text.y = element_text(size = 14),
                axis.text.x = element_text(size = 14, face = "bold",angle = 45, hjust = 1, vjust = 1),
                axis.title.y = element_text(size = 16, face = "bold"),
                plot.title = element_text(size = 20, face = "bold",hjust = 0.5)) +
            theme(legend.position = "none")

library(datasets)
library(ggplot2)
library(tidyr)
library(dplyr)

NewOA <- outputArray[,16:20] %>%
  mutate(across(everything(), ~ . / 1e3)) %>%
  pivot_longer(
    cols = everything(),     # Include all columns
    names_to = "Variable",   # New column for variable names
    values_to = "Value"      # New column for the values
  ) %>%
  group_by(Variable) %>%
  mutate(paired = seq_len(n())) %>% # Use seq_len(n()) to avoid potential issues with length
  ungroup() %>%
  mutate(
    Variable = factor(Variable, levels = c(
      "NoVacHosp",
      "Neonatal1_6_10Hosp",
      "Rotarix6_10Hosp",
      "Rotarix6_10_14Hosp",
      "Rotarix6_10_40Hosp"
    )) # Explicitly set the order
  )

hosp <- ggplot(data = NewOA,
            mapping = aes(x = Variable, y = Value, fill = Variable)) +
            ggtitle("Hospitalizations") +
            geom_line(mapping = aes(group = paired), 
                      position = position_dodge(0.1), 
                      alpha = 0.1,   # Increase transparency for lines
                      color = "grey46", # Set a lighter color for the lines
                      linewidth = 0.25 # Use a thinner line
                      ) +
            geom_violin() +
            geom_point(mapping = aes(fill = Variable, group = paired),
                       size = 0.25, shape = 21,
                       position = position_dodge(0.1)) +
            scale_fill_manual(
              values = c(
                "NoVacHosp" = "#595959FF",      # Blue
                "Neonatal1_6_10Hosp" = "#FF800EFF",
                "Rotarix6_10Hosp" = "#CA0020", # Green
                "Rotarix6_10_14Hosp" = "#006BA4FF", # Red
                "Rotarix6_10_40Hosp" = "#ABABABFF"  # Purple
              )
            ) +
            scale_x_discrete(labels = Labels) + scale_y_continuous(limits = c(150, 500)) +
              theme_classic() + xlab(NULL) + ylab("Hospitalizations (thousands)") +
               theme(axis.text.y = element_text(size = 14),
                axis.text.x = element_text(size = 14, face = "bold",angle = 45, hjust = 1, vjust = 1),
                axis.title.y = element_text(size = 16, face = "bold"),
                plot.title = element_text(size = 20, face = "bold",hjust = 0.5)) +
            theme(legend.position = "none")
NewOA <- outputArray[,53:57] %>%
  mutate(across(everything(), ~ . / 1e3)) %>%
  pivot_longer(
    cols = everything(),     # Include all columns
    names_to = "Variable",   # New column for variable names
    values_to = "Value"      # New column for the values
  ) %>%
  group_by(Variable) %>%
  mutate(paired = seq_len(n())) %>% # Use seq_len(n()) to avoid potential issues with length
  ungroup() %>%
  mutate(
    Variable = factor(Variable, levels = c(
      "NoVacDALYs",
      "Neonatal1_6_10DALYs",
      "Rotarix6_10DALYs",
      "Rotarix6_10_14DALYs",
      "Rotarix6_10_40DALYs"
    )) # Explicitly set the order
  )

dalys <- ggplot(data = NewOA,
            mapping = aes(x = Variable, y = Value, fill = Variable)) +
            ggtitle("DALYs") +
            geom_line(mapping = aes(group = paired), 
                      position = position_dodge(0.1), 
                      alpha = 0.1,   # Increase transparency for lines
                      color = "grey46", # Set a lighter color for the lines
                      linewidth = 0.25 # Use a thinner line
                      ) +
            geom_violin() +
            geom_point(mapping = aes(fill = Variable, group = paired),
                       size = 0.25, shape = 21,
                       position = position_dodge(0.1)) +
            scale_fill_manual(
              values = c(
                "NoVacDALYs" = "#595959FF",      # Blue
                "Neonatal1_6_10DALYs" = "#FF800EFF",
                "Rotarix6_10DALYs" = "#CA0020", # Green
                "Rotarix6_10_14DALYs" = "#006BA4FF", # Red
                "Rotarix6_10_40DALYs" = "#ABABABFF"  # Purple
              )
            ) +
            scale_x_discrete(labels = Labels) + scale_y_continuous(limits = c(0, NA)) +
              theme_classic() + xlab(NULL) + ylab("DALYs  (thousands)") +
               theme(axis.text.y = element_text(size = 14),
                axis.text.x = element_text(size = 14, face = "bold",angle = 45, hjust = 1, vjust = 1),
                axis.title.y = element_text(size = 16, face = "bold"),
                plot.title = element_text(size = 20, face = "bold",hjust = 0.5)) +
            theme(legend.position = "none")

NewOA <- outputArray[,21:25] %>%
  mutate(across(everything(), ~ . / 1e3)) %>%
  pivot_longer(
    cols = everything(),     # Include all columns
    names_to = "Variable",   # New column for variable names
    values_to = "Value"      # New column for the values
  ) %>%
  group_by(Variable) %>%
  mutate(paired = seq_len(n())) %>% # Use seq_len(n()) to avoid potential issues with length
  ungroup() %>%
  mutate(
    Variable = factor(Variable, levels = c(
      "NoVacDeaths",
      "Neonatal1_6_10Deaths",
      "Rotarix6_10Deaths",
      "Rotarix6_10_14Deaths",
      "Rotarix6_10_40Deaths"
    )) # Explicitly set the order
  )

deaths <- ggplot(data = NewOA,
            mapping = aes(x = Variable, y = Value, fill = Variable)) +
            ggtitle("Deaths") +
            geom_line(mapping = aes(group = paired), 
                      position = position_dodge(0.1), 
                      alpha = 0.1,   # Increase transparency for lines
                      color = "grey46", # Set a lighter color for the lines
                      linewidth = 0.25 # Use a thinner line
                      ) +
            geom_violin() +
            geom_point(mapping = aes(fill = Variable, group = paired),
                       size = 0.25, shape = 21,
                       position = position_dodge(0.1)) +
            scale_fill_manual(
              values = c(
                "NoVacDeaths" = "#595959FF",      # Blue
                "Neonatal1_6_10Deaths" = "#FF800EFF",
                "Rotarix6_10Deaths" = "#CA0020", # Green
                "Rotarix6_10_14Deaths" = "#006BA4FF", # Red
                "Rotarix6_10_40Deaths" = "#ABABABFF"  # Purple
              )
            ) +
            scale_x_discrete(labels = Labels) + scale_y_continuous(limits = c(0, NA)) +
              theme_classic() + xlab(NULL) + ylab("Deaths (thousands)") +
               theme(axis.text.y = element_text(size = 14),
                axis.text.x = element_text(size = 14, face = "bold",angle = 45, hjust = 1, vjust = 1),
                axis.title.y = element_text(size = 16, face = "bold"),
                plot.title = element_text(size = 20, face = "bold",hjust = 0.5)) +
            theme(legend.position = "none")

cases
ggsave("CasesPlot.png", path ="~")
hosp
ggsave("HospPlot.png", path ="~")
dalys
ggsave("DALYsPlot.png", path ="~")
deaths
ggsave("DeathsPlot.png", path ="~")
combined_plot <- cases + hosp +  dalys + deaths +
  plot_layout(ncol = 2) # Set number of columns

# Display the combined plot
print(combined_plot)
ggsave("Plots1.png", path ="~",width = 15, height = 12, dpi = 300)

```

## Tables

```{r}
#### Table 1
labs <- c("No Vaccination", "1/6/10","6/10","6/10/14","6/10/40")
costdata <- c(IntCost_NoVac,IntCost_Neonatal1_6_10,IntCost_Rotarix6_10,IntCost_Rotarix6_10_14,IntCost_Rotarix6_10_40,
              TrtCost_NoVac,TrtCost_Neonatal1_6_10,TrtCost_Rotarix6_10,TrtCost_Rotarix6_10_14,TrtCost_Rotarix6_10_40,
              TotCost_NoVac,TotCost_Neonatal1_6_10,TotCost_Rotarix6_10,TotCost_Rotarix6_10_14, TotCost_Rotarix6_10_40,
              costDiffNoVac,costDiff1_6_10,NA,costDiff6_10_14,costDiff6_10_40)

costdata <- round(costdata,-5)
a <- costdata[1:5]
b <- costdata[6:10]
c <- costdata[11:15]
d <- costdata[16:20]
table4 <- data.frame(labs,a,b,c,d)

table4 |>
  gt() |>
  tab_header(
    title = "Costs by Vaccine Schedule",
    subtitle = glue::glue("Government Perspective - Compared to the 6/10 Rotarix Schedule")
  ) |>
  cols_label(labs = " ",a="Intervention Cost",b="Treatment Cost",c="Total Cost", d="Cost Difference")|>
  fmt_currency(
    columns = c(a,b,c,d),
    currency = "USD",
    decimals=0
  )|> gtsave(filename = "CostByScheduleT1P.png",path ="~")


#### Table 2

Number_Cases <- c("No Vaccination","Neonatal 1/6/10","Rotarix 6/10","Rotarix 6/10/14", "Rotarix 6/10/40")
averted <- c(round(mean(outputArray$NumCases_NoVac),-2),round(mean(outputArray$NumCases_Neonatal1_6_10),-2),
             round(mean(outputArray$NumCases_Rotarix6_10),-2),round(mean(outputArray$NumCases_Rotarix6_10_14),-2),
             round(mean(outputArray$NumCases_Rotarix6_10_40),-2),round(mean(outputArray$MSCases_NoVac),-2),
             round(mean(outputArray$MSCases_Neonatal1_6_10),-2),round(mean(outputArray$MSCases_Rotarix6_10),-2),
             round(mean(outputArray$MSCases_Rotarix6_10_14),-2),round(mean(outputArray$MSCases_Rotarix6_10_40),-2),
             round(mean(outputArray$NSCases_NoVac),-2),round(mean(outputArray$NSCases_Neonatal1_6_10),-2),
             round(mean(outputArray$NSCases_Rotarix6_10),-2),round(mean(outputArray$NSCases_Rotarix6_10_14),-2),
             round(mean(outputArray$NSCases_Rotarix6_10_40),-2),
             round(mean(outputArray$NoVacHosp),-2),round(mean(outputArray$Neonatal1_6_10Hosp),-2),
             round(mean(outputArray$Rotarix6_10Hosp),-2),round(mean(outputArray$Rotarix6_10_14Hosp),-2),
             round(mean(outputArray$Rotarix6_10_40Hosp),-2),round(mean(outputArray$NoVacDALYs),-2),
             round(mean(outputArray$Neonatal1_6_10DALYs),-2),round(mean(outputArray$Rotarix6_10DALYs),-2),
             round(mean(outputArray$Rotarix6_10_14DALYs),-2),round(mean(outputArray$Rotarix6_10_40DALYs),-2),
             round(mean(outputArray$NoVacDeaths),-2),round(mean(outputArray$Neonatal1_6_10Deaths),-2),
             round(mean(outputArray$Rotarix6_10Deaths),-2),round(mean(outputArray$Rotarix6_10_14Deaths),-2),
             round(mean(outputArray$Rotarix6_10_40Deaths),-2))
z <- averted[1:5]
x <- averted[6:10]
a <- averted[11:15]
b <- averted[16:20]
c <- averted[21:25]
d <- averted[26:30]
table2 <- data.frame(Number_Cases,z,x,a,b,c,d)

table2 |>
  gt() |>
  tab_header(
    title = "Outcomes by Vaccine Schedule",
    subtitle = glue::glue(" ")
  )  |>
  cols_label(Number_Cases=" ",z="Total Cases (n)",x="Moderate-Severe Cases (n)",a="Non-Severe Cases (n)",b="Hospitalizations (n)",c="DALYs (n)",d="Deaths (n)"
  )|> gtsave(filename = "OutcomesT2P.png",path ="~")
#####################
Number_Averted <- c("No Vaccine", "Neonatal 1/6/10","Rotarix 6/10","Rotarix 6/10/14", "Rotarix 6/10/40")
averted <- c(#cost
             round(TotCost_NoVac,-5),round(TotCost_Neonatal1_6_10,-5),round(TotCost_Rotarix6_10,-5),
             round(TotCost_Rotarix6_10_14,-5),round(TotCost_Rotarix6_10_40,-5),
             #DALYs
             round(DALYs_NoVac,-2),round(DALYs_Neonatal1_6_10,-2),round(DALYs_Rotarix6_10,-2),
             round(DALYs_Rotarix6_10_14,-2),round(DALYs_Rotarix6_10_40,-2),
             #DALYs Averted
             round(DALYsavNV,-2),round(DALYsavN10,-2),NA,round(DALYsav14,-2),round(DALYsav40,-2),
             #cost per DALY averted
             round(costDALYAvNV,2),costDALYAv1_6_10,NA,round(costDALYAv6_10_14,2),round(costDALYAv6_10_40,2),
             # NA,"Cost-saving",NA,"$49","$75",
             #ICER
             "--",round(mean(outputArray$ICERatio_Neonatal1_6_10),1),
             round(mean(outputArray$ICERatio_Rotarix6_10),1),round(mean(outputArray$ICERatio_Rotarix6_10_14),1),
             round(mean(outputArray$ICERatio_Rotarix6_10_40),1))
             # "--",round(mean(outputArray$ICERatio_Neonatal1_6_10),1),"Strongly Dominated","Strongly Dominated","Strongly Dominated")
z <- as.numeric(averted[1:5])
x <- averted[6:10]
a <- averted[11:15]
b <- averted[16:20]
c <- averted[21:25]

table3 <- data.frame(Number_Averted,z,x,a,b,c)

table3 |>
  gt() |>
  tab_header(
    title = "Cost-Effectiveness Comparison of All Vaccine Strategies",
    subtitle = glue::glue("Government Perspective - Compared to the 6/10 Rotarix Schedule")
  )  |>
  cols_label(Number_Averted=" ",z="Cost",x="DALYs (n)",a="DALYs Averted (n)",b="Cost per DALY averted", c="ICER")|>
  fmt_currency(
    columns = c(z),
    currency = "USD",
    decimals=0
  )|>
  tab_footnote(
    footnote = "No DALYs averted.",
    locations = cells_body(columns = b, rows = 1)
  )|> gtsave(filename = "CostAndOutcomesP.png",path ="~")

```


Quantiles

```{r}
## Prediction Intervals for each MEAN
#total cost
TotCost_NoVac          <- quantile(outputArray$NoVacCost,c(0.025,0.975))
TotCost_Rotarix6_10    <- quantile(outputArray$Rotarix6_10Cost,c(0.025,0.975))
TotCost_Rotarix6_10_14 <- quantile(outputArray$Rotarix6_10_14Cost,c(0.025,0.975))
TotCost_Rotarix6_10_40 <- quantile(outputArray$Rotarix6_10_40Cost,c(0.025,0.975))
TotCost_Neonatal1_6_10 <- quantile(outputArray$Neonatal1_6_10Cost,c(0.025,0.975))
#intervention cost
IntCost_NoVac          <- quantile(outputArray$NoVacCostInt,c(0.025,0.975))
IntCost_Rotarix6_10    <- quantile(outputArray$Rotarix6_10CostInt,c(0.025,0.975))
IntCost_Rotarix6_10_14 <- quantile(outputArray$Rotarix6_10_14CostInt,c(0.025,0.975))
IntCost_Rotarix6_10_40 <- quantile(outputArray$Rotarix6_10_40CostInt,c(0.025,0.975))
IntCost_Neonatal1_6_10 <- quantile(outputArray$Neonatal1_6_10CostInt,c(0.025,0.975))
#treatment cost
TrtCost_NoVac          <- quantile(outputArray$NoVacCostTrt,c(0.025,0.975))
TrtCost_Rotarix6_10    <- quantile(outputArray$Rotarix6_10CostTrt,c(0.025,0.975))
TrtCost_Rotarix6_10_14 <- quantile(outputArray$Rotarix6_10_14CostTrt,c(0.025,0.975))
TrtCost_Rotarix6_10_40 <- quantile(outputArray$Rotarix6_10_40CostTrt,c(0.025,0.975))
TrtCost_Neonatal1_6_10 <- quantile(outputArray$Neonatal1_6_10CostTrt,c(0.025,0.975))


NumCases_NoVac          <- quantile(outputArray$NumCases_NoVac,c(0.025,0.975))
NumCases_Neonatal1_6_10 <- quantile(outputArray$NumCases_Neonatal1_6_10,c(0.025,0.975))
NumCases_Rotarix6_10    <- quantile(outputArray$NumCases_Rotarix6_10,c(0.025,0.975))
NumCases_Rotarix6_10_14 <- quantile(outputArray$NumCases_Rotarix6_10_14,c(0.025,0.975))
NumCases_Rotarix6_10_40 <- quantile(outputArray$NumCases_Rotarix6_10_40,c(0.025,0.975))
MSCases_NoVac          <- quantile(outputArray$MSCases_NoVac,c(0.025,0.975))
MSCases_Neonatal1_6_10 <- quantile(outputArray$MSCases_Neonatal1_6_10,c(0.025,0.975))
MSCases_Rotarix6_10    <- quantile(outputArray$MSCases_Rotarix6_10,c(0.025,0.975))
MSCases_Rotarix6_10_14 <- quantile(outputArray$MSCases_Rotarix6_10_14,c(0.025,0.975))
MSCases_Rotarix6_10_40 <- quantile(outputArray$MSCases_Rotarix6_10_40,c(0.025,0.975))
NSCases_NoVac          <- quantile(outputArray$NSCases_NoVac,c(0.025,0.975))
NSCases_Neonatal1_6_10 <- quantile(outputArray$NSCases_Neonatal1_6_10,c(0.025,0.975))
NSCases_Rotarix6_10    <- quantile(outputArray$NSCases_Rotarix6_10,c(0.025,0.975))
NSCases_Rotarix6_10_14 <- quantile(outputArray$NSCases_Rotarix6_10_14,c(0.025,0.975))
NSCases_Rotarix6_10_40 <- quantile(outputArray$NSCases_Rotarix6_10_40,c(0.025,0.975))
NoVacHosp               <- quantile(outputArray$NoVacHosp,c(0.025,0.975))
Neonatal1_6_10Hosp      <- quantile(outputArray$Neonatal1_6_10Hosp,c(0.025,0.975))
Rotarix6_10Hosp         <- quantile(outputArray$Rotarix6_10Hosp,c(0.025,0.975))
Rotarix6_10_14Hosp      <- quantile(outputArray$Rotarix6_10_14Hosp,c(0.025,0.975))
Rotarix6_10_40Hosp      <- quantile(outputArray$Rotarix6_10_40Hosp,c(0.025,0.975))
NoVacDALYs              <- quantile(outputArray$NoVacDALYs,c(0.025,0.975))
Neonatal1_6_10DALYs     <- quantile(outputArray$Neonatal1_6_10DALYs,c(0.025,0.975))
Rotarix6_10DALYs        <- quantile(outputArray$Rotarix6_10DALYs,c(0.025,0.975))
Rotarix6_10_14DALYs     <- quantile(outputArray$Rotarix6_10_14DALYs,c(0.025,0.975))
Rotarix6_10_40DALYs     <- quantile(outputArray$Rotarix6_10_40DALYs,c(0.025,0.975))
NoVacDeaths             <- quantile(outputArray$NoVacDeaths,c(0.025,0.975))
Neonatal1_6_10Deaths    <- quantile(outputArray$Neonatal1_6_10Deaths,c(0.025,0.975))
Rotarix6_10Deaths       <- quantile(outputArray$Rotarix6_10Deaths,c(0.025,0.975))
Rotarix6_10_14Deaths    <- quantile(outputArray$Rotarix6_10_14Deaths,c(0.025,0.975))
Rotarix6_10_40Deaths    <- quantile(outputArray$Rotarix6_10_40Deaths,c(0.025,0.975))


#dalys
DALYs_NoVac          <- quantile(outputArray$NoVacDALYs,c(0.025,0.975))
DALYs_Rotarix6_10    <- quantile(outputArray$Rotarix6_10DALYs,c(0.025,0.975))
DALYs_Rotarix6_10_14 <- quantile(outputArray$Rotarix6_10_14DALYs,c(0.025,0.975))
DALYs_Rotarix6_10_40 <- quantile(outputArray$Rotarix6_10_40DALYs,c(0.025,0.975))
DALYs_Neonatal1_6_10 <- quantile(outputArray$Neonatal1_6_10DALYs,c(0.025,0.975))

#cost difference
costDiffNoVac   <- TotCost_NoVac - TotCost_Rotarix6_10
costDiff6_10_14 <- TotCost_Rotarix6_10_14 - TotCost_Rotarix6_10
costDiff6_10_40 <- TotCost_Rotarix6_10_40 - TotCost_Rotarix6_10
costDiff1_6_10  <- TotCost_Neonatal1_6_10 - TotCost_Rotarix6_10

#average outcomes averted
CasesavNV   <- quantile(outputArray$CasesAverted_NoVac,c(0.025,0.975))
Casesav14   <- quantile(outputArray$CasesAverted_Rotarix6_10_14,c(0.025,0.975))
Casesav40   <- quantile(outputArray$CasesAverted_Rotarix6_10_40,c(0.025,0.975))
CasesavN10  <- quantile(outputArray$CasesAverted_Neonatal1_6_10,c(0.025,0.975))
HospsavNV   <- quantile(outputArray$HospAverted_NoVac,c(0.025,0.975))
Hospsav14   <- quantile(outputArray$HospAverted_Rotarix6_10_14,c(0.025,0.975))
Hospsav40   <- quantile(outputArray$HospAverted_Rotarix6_10_40,c(0.025,0.975))
HospsavN10  <- quantile(outputArray$HospAverted_Neonatal1_6_10,c(0.025,0.975))
DALYsavNV   <- quantile(outputArray$DALYsAverted_NoVac,c(0.025,0.975))
DALYsav14   <- quantile(outputArray$DALYsAverted_Rotarix6_10_14,c(0.025,0.975))
DALYsav40   <- quantile(outputArray$DALYsAverted_Rotarix6_10_40,c(0.025,0.975))
DALYsavN10  <- quantile(outputArray$DALYsAverted_Neonatal1_6_10,c(0.025,0.975))
DeathsavNV  <- quantile(outputArray$DeathsAverted_NoVac,c(0.025,0.975))
Deathsav14  <- quantile(outputArray$DeathsAverted_Rotarix6_10_14,c(0.025,0.975))
Deathsav40  <- quantile(outputArray$DeathsAverted_Rotarix6_10_40,c(0.025,0.975))
DeathsavN10 <- quantile(outputArray$DeathsAverted_Neonatal1_6_10,c(0.025,0.975))
#costs per outcome averted
costCaseAvNV        <- costDiffNoVac/CasesavNV
costCaseAv6_10_14   <- costDiff6_10_14/Casesav14
costCaseAv6_10_40   <- costDiff6_10_40/Casesav40
costCaseAv1_6_10    <- costDiff1_6_10/CasesavN10
costHospAvNV        <- costDiffNoVac/HospsavNV
costHospAv6_10_14   <- costDiff6_10_14/Hospsav14
costHospAv6_10_40   <- costDiff6_10_40/Hospsav40
costHospAv1_6_10    <- costDiff1_6_10/HospsavN10
costDALYAvNV        <- costDiffNoVac/DALYsavNV
costDALYAv6_10_14   <- costDiff6_10_14/DALYsav14
costDALYAv6_10_40   <- costDiff6_10_40/DALYsav40
costDALYAv1_6_10    <- costDiff1_6_10/DALYsavN10
costDeathAvNV       <- costDiffNoVac/DeathsavNV
costDeathAv6_10_14  <- costDiff6_10_14/Deathsav14
costDeathAv6_10_40  <- costDiff6_10_40/Deathsav40
costDeathAv1_6_10   <- costDiff1_6_10/DeathsavN10

ICERatio_Neonatal1_6_10 <- quantile(outputArray$ICERatio_Neonatal1_6_10,c(0.025,0.975))
ICERatio_Rotarix6_10    <- quantile(outputArray$ICERatio_Rotarix6_10,c(0.025,0.975))
ICERatio_Rotarix6_10_14 <- quantile(outputArray$ICERatio_Rotarix6_10_14,c(0.025,0.975))
ICERatio_Rotarix6_10_40 <- quantile(outputArray$ICERatio_Rotarix6_10_40,c(0.025,0.975))

#outcome numbers
NumCases_NoVac 
NumCases_Neonatal1_6_10 
NumCases_Rotarix6_10
NumCases_Rotarix6_10_14
NumCases_Rotarix6_10_40
MSCases_NoVac 
MSCases_Neonatal1_6_10 
MSCases_Rotarix6_10
MSCases_Rotarix6_10_14
MSCases_Rotarix6_10_40
NSCases_NoVac 
NSCases_Neonatal1_6_10 
NSCases_Rotarix6_10
NSCases_Rotarix6_10_14
NSCases_Rotarix6_10_40
NoVacHosp 
Neonatal1_6_10Hosp
Rotarix6_10Hosp 
Rotarix6_10_14Hosp
Rotarix6_10_40Hosp
NoVacDALYs
Neonatal1_6_10DALYs
Rotarix6_10DALYs
Rotarix6_10_14DALYs
Rotarix6_10_40DALYs
NoVacDeaths
Neonatal1_6_10Deaths
Rotarix6_10Deaths
Rotarix6_10_14Deaths
Rotarix6_10_40Deaths
#dalys
DALYs_NoVac
DALYs_Rotarix6_10   
DALYs_Rotarix6_10_14
DALYs_Rotarix6_10_40
DALYs_Neonatal1_6_10
```
